/**
 * App: Shopping Cart API
 * Package: com.bobwares.shoppingcart.config
 * File: AppProperties.java
 * Version: 0.1.0
 * Turns: 1
 * Author: gpt-5-codex
 * Date: 2025-10-02T23:02:16Z
 * Exports: AppProperties
 * Description: Defines validated configuration properties for the Shopping Cart API.
 *              Accessors generated by Lombok expose the configuration values.
 */
package com.bobwares.shoppingcart.config;

import jakarta.validation.constraints.DecimalMin;
import jakarta.validation.constraints.Max;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotEmpty;
import jakarta.validation.constraints.NotNull;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import lombok.Getter;
import lombok.Setter;
import org.springframework.boot.context.properties.ConfigurationProperties;
import org.springframework.validation.annotation.Validated;

/**
 * Strongly typed configuration exposed under the {@code app} prefix to control runtime metadata.
 */
@Getter
@Setter
@Validated
@ConfigurationProperties(prefix = "app")
public class AppProperties {

  /** Name displayed for the running application instance. */
  @NotBlank
  private String name = "backend";

  /** Network port the application listens on. */
  @NotNull
  @Min(1)
  @Max(65535)
  private Integer port = 8080;

  /** Default tax rate applied when order-level overrides are absent. */
  @NotNull
  @DecimalMin("0.00")
  private BigDecimal defaultTaxRate = BigDecimal.ZERO;

  /** Baseline shipping cost before promotional adjustments. */
  @NotNull
  @DecimalMin("0.00")
  private BigDecimal defaultShippingCost = BigDecimal.ZERO;

  /** List of ISO currency codes the API accepts for pricing operations. */
  @NotNull
  @NotEmpty
  private List<String> supportedCurrencies = new ArrayList<>(List.of("USD"));
}
