# /**
#  * App: Shopping Cart API
#  * Package: resources
#  * File: application.yml
#  * Version: 0.1.0
#  * Turns: 1
#  * Author: Codex Agent
#  * Date: 2025-10-01T19:32:32Z
#  * Exports: spring configuration
#  * Description: Configures Spring Boot, datasource, Liquibase, and OpenAPI settings for the Shopping Cart API.
#  */
spring:
  application:
    name: ${APP_NAME}
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: false
        default_schema: ${DATABASE_SCHEMA}
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml
    enabled: true
server:
  port: ${APP_PORT}
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
  health:
    db:
      enabled: true
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
app:
  app-name: ${APP_NAME}
  app-port: ${APP_PORT}
  db-host: ${DATABASE_HOST}
  db-port: ${DATABASE_PORT}
  db-name: ${DATABASE_NAME}
  db-username: ${DATABASE_USERNAME}
  db-password: ${DATABASE_PASSWORD}
  db-schema: ${DATABASE_SCHEMA}
