spring:
  application:
    name: ${APP_NAME:backend}
  main:
    banner-mode: "console"
  output:
    ansi:
      enabled: DETECT

server:
  port: ${PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized

app:
  name: ${APP_NAME:backend}
  port: ${PORT:8080}
